apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-main
  labels:
    group: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
      tier: infrastructure
  template:
    metadata:
      labels:
        app: nats
        tier: infrastructure
    spec:
      containers:
        - name: nats-main
          image: nats
          args:
            [
              "-p",
              "4222",

              "--http_port",
              "8222",

              "--cluster_name",
              "nats-cluster",

              "--cluster",
              "nats://0.0.0.0:6222",

              "-DV"
            ]
