apiVersion: v1
kind: Service
metadata:
  name: nats-service-main
spec:
  selector:
    app: nats
    tier: infrastructure
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: cluster
      protocol: TCP
      port: 6222
      targetPort: 6222
    - name: http-reporting
      protocol: TCP
      port: 8222
      targetPort: 8222
#  type: LoadBalancer